CREATE TABLE USER
(
    ID           INT AUTO_INCREMENT,
    ACCOUNT_ID   VARCHAR(100),
     NAME         VARCHAR(50),
    TOKEN        CHAR(36),
    GMT_CREATE   BIGINT,
    GMT_MODIFIED BIGINT,
    CONSTRAINT USER_PK
        PRIMARY KEY (ID)
);

